CREATE TABLE IF NOT EXISTS PDF_GENERATION(
PDF_ID INTEGER PRIMARY KEY,
CUST_ID INTEGER,
CUST_NAME VARCHAR,
INVOICE_NAME VARCHAR,
INVOICE_PDF bytea,
CREATED_DATE DATE,
USER_ID INTEGER
);
CREATE TABLE IF NOT EXISTS PDF_TEMPLATE(
T_ID INTEGER PRIMARY KEY,
USER_ID INTEGER,
H1_FONT VARCHAR,
H1_SIZE DECIMAL,
H1_POSITION VARCHAR,
H2_FONT VARCHAR,
H2_SIZE INTEGER,
H2_POSITION VARCHAR,
I_FONT VARCHAR,
I_SIZE INTEGER,
I_TYPOGRAPHY VARCHAR,
CURRENCY VARCHAR
LOGO bytea,
LOGO_POSITION VARCHAR,
LOGO_SIZE INTEGER[]
);